{% set name = "colcon-output" %}
{% set version = "0.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 925f02cda3487abb0156da8911e1797dae1701d1c581cd1243202edb69410bfc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - colcon-core >=0.3.8

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to customize the output in various ways.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
