{% set name = "colcon-output" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5e3fc56ff50e0ce894ae912a8a2225fc6349e9bc8eb7b6e1c9d472416e35406a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - colcon-core >=0.3.8

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    An extension for colcon-core to customize the output in various ways.

extra:
  recipe-maintainers:
    - j-rivero
    - seanyen
    - wolfv
